# coding: utf-8

"""
    barcodeapi

    Barcode APIs let you generate barcode images, and recognize values from images of barcodes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_barcode_api_client
from cloudmersive_barcode_api_client.api.generate_barcode_api import GenerateBarcodeApi  # noqa: E501
from cloudmersive_barcode_api_client.rest import ApiException


class TestGenerateBarcodeApi(unittest.TestCase):
    """GenerateBarcodeApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_barcode_api_client.api.generate_barcode_api.GenerateBarcodeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_barcode_ean13(self):
        """Test case for generate_barcode_ean13

        Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode  # noqa: E501
        """
        pass

    def test_generate_barcode_ean8(self):
        """Test case for generate_barcode_ean8

        Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode  # noqa: E501
        """
        pass

    def test_generate_barcode_qr_code(self):
        """Test case for generate_barcode_qr_code

        Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information  # noqa: E501
        """
        pass

    def test_generate_barcode_upca(self):
        """Test case for generate_barcode_upca

        Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode  # noqa: E501
        """
        pass

    def test_generate_barcode_upce(self):
        """Test case for generate_barcode_upce

        Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
