# coding: utf-8

"""
    barcodeapi

    Barcode APIs let you generate barcode images, and recognize values from images of barcodes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_barcode_api_client
from cloudmersive_barcode_api_client.models.product_match import ProductMatch  # noqa: E501
from cloudmersive_barcode_api_client.rest import ApiException


class TestProductMatch(unittest.TestCase):
    """ProductMatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductMatch(self):
        """Test ProductMatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_barcode_api_client.models.product_match.ProductMatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
