# coding: utf-8

"""
    barcodeapi

    Barcode APIs let you generate barcode images, and recognize values from images of barcodes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_barcode_api_client
from cloudmersive_barcode_api_client.api.barcode_scan_api import BarcodeScanApi  # noqa: E501
from cloudmersive_barcode_api_client.rest import ApiException


class TestBarcodeScanApi(unittest.TestCase):
    """BarcodeScanApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_barcode_api_client.api.barcode_scan_api.BarcodeScanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_barcode_scan_image(self):
        """Test case for barcode_scan_image

        Scan an image for a barcode and turn the result.  Supported barcode types include AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
