# coding: utf-8

"""
    barcodeapi

    Barcode APIs let you generate barcode images, and recognize values from images of barcodes.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_barcode_api_client
from cloudmersive_barcode_api_client.api.barcode_lookup_api import BarcodeLookupApi  # noqa: E501
from cloudmersive_barcode_api_client.rest import ApiException


class TestBarcodeLookupApi(unittest.TestCase):
    """BarcodeLookupApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_barcode_api_client.api.barcode_lookup_api.BarcodeLookupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_barcode_lookup_ean_lookup(self):
        """Test case for barcode_lookup_ean_lookup

        Lookup a barcode value and return product data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
